---
- hosts: localhost
  vars:
   host: "10.172.10.1"
   username: "userxx"
   vdom: "root"
   ssl_verify: "False"
  vars_prompt:
  - name: password
    prompt: "Type the password of your fortigate admin account"
    private: no
  tasks:
  - name: Configure dhcp server
    fortios_system_dhcp_server:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "False"
      state: "present"
      system_dhcp_server:
        interface: "vlan_101"
        auto_configuration: "disable"
        id: "101"
        ip_mode: "range"
        ip_range:
         -
           start_ip: "10.172.101.10"
           id:  "101"
           end_ip: "10.172.101.20"
        netmask: "255.255.255.0"
        default_gateway: "10.172.101.1"
        dns_service: "default"
        timezone_option: "default"
        server_type: "regular"
        ntp_service: "default"
        status: "enable"
        lease_time: "28800"
        state: "present"

# edit 2
#        set dns-service default
#        set default-gateway 10.172.101.1
#        set netmask 255.255.255.0
#        set interface "vlan_101"
#        config ip-range
#            edit 1
#                set start-ip 10.172.101.2
#                set end-ip 10.172.101.254
#            next
#        end
#        set timezone-option default
#    next