---
-  hosts: localhost
   connection: local
   gather_facts: yes
   vars:
    vmwhostname: vcenter.ansible.local
    vmwusername: administrator@vsphere.local
    vmwpassword: Only4Demo!
    esxihostname: esxi.ansible.local
   tasks:
   - name: Change NFS.MaxVolumes setting for an ESXi host
     vmware_host_config_manager:
       hostname: "{{ vmwhostname }}"
       username: "{{ vmwusername }}"
       password: "{{ vmwpassword }}"
       validate_certs: False
       esxi_hostname: "{{ esxihostname }}"
       options:
         'NFS.MaxVolumes': '16'
         'NFS41.MaxVolumes': '16'

   - name: Clone fedora 30 to storage.ansible.local
     vmware_guest:
       hostname: "{{ vmwhostname }}"
       username: "{{ vmwusername }}"
       password: "{{ vmwpassword }}"
       validate_certs: False
       name: storage.ansible.local
       template: _TEMP_fedora30
       datacenter: Datacenter
       folder: /Admin
       state: poweredon
       wait_for_ip_address: yes
     register: storagevm

   - name: IP address info
     debug:
       msg: "{{ storagevm.instance.ipv4 }}"

   - name: Set Fact storagevm_ip_fact
     set_fact:
      storagevm_ip_fact: "{{ storagevm.instance.ipv4 }}"

   - name: IP address info
     debug:
       msg: "{{ storagevm_ip_fact }}"   

   - name: add storagevm to ansible host file
     add_host:
      name: "{{ storagevm_ip_fact }}"
      groups: storagetmp

-  hosts: storagetmp
   tasks:
   - name: Test file
     file:
       path: /home/jesbe/testfile.txt
       state: touch