---
-  hosts: localhost
   connection: local
   gather_facts: yes
   vars:
    vmwhostname: vcenter.ansible.local
    vmwusername: administrator@vsphere.local
    vmwpassword: Only4Demo!
    esxihostname: esxi.ansible.local
   tasks:
   - name: Clone fedora 30 to storage.ansible.local
     vmware_guest:
       hostname: "{{ vmwhostname }}"
       username: "{{ vmwusername }}"
       password: "{{ vmwpassword }}"
       validate_certs: False
       name: storage.ansible.local
       template: _TEMP_fedora30
       datacenter: Datacenter
       folder: /Admin
       state: poweredon
       wait_for_ip_address: yes

   - name: Change NFS.MaxVolumes setting for an ESXi host
     vmware_host_config_manager:
       hostname: "{{ vmwihostname }}"
       username: "{{ vmwusername }}"
       password: "{{ vmwpassword }}"
       validate_certs: False
       esxi_hostname: "{{ esxihostname }}"
       options:
         'NFS.MaxVolumes': '16'
         'NFS41.MaxVolumes': '16'
       delegate_to: localhost